apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: krp
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: k8s_reliability
  APP_ENV: development
  LOG_LEVEL: info
  SERVICE_NAME: order-service
  HOST: "0.0.0.0"
  PORT: "8002"
  PAYMENT_SERVICE_URL: http://payment-service:8003
  PAYMENT_SERVICE_TIMEOUT_SECONDS: "5.0"
