{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ include "krp.namespace" . }}
  labels:
    app: otel-collector
    {{- include "krp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: {{ .Values.otelCollector.service.otlpGrpcPort }}
      targetPort: {{ .Values.otelCollector.service.otlpGrpcPort }}
{{- end }}
