apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: krp
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: k8s_reliability
  APP_ENV: development
  LOG_LEVEL: info
  SERVICE_NAME: payment-service
  HOST: "0.0.0.0"
  PORT: "8003"
